#Use base image node 
FROM node:alpine

WORKDIR '/app'

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json .
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
RUN npm install react-redux
RUN npm install redux
RUN npm install redux-thunk
COPY . .
# start app
CMD ["npm", "start"]