version: '3'
services:
    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - '/app/node_modules'
            - './frontend:/app'
        stdin_open: true
        command: ["npm", "run", "start"]
        #   depends_on:
        #     - backend
    backend:
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        command: rails server -p 3001 -b '0.0.0.0'
        volumes:
            - '/app/node_modules'
            - './backend:/app'
        ports:
            - "3001:3001"